module ISeqBuilder
  RUBY_ID_STATIC_SYM  = 0x01
  RUBY_ID_LOCAL       = 0x00
  RUBY_ID_INSTANCE    = (0x01<<1)
  RUBY_ID_GLOBAL      = (0x03<<1)
  RUBY_ID_ATTRSET     = (0x04<<1)
  RUBY_ID_CONST       = (0x05<<1)
  RUBY_ID_CLASS       = (0x06<<1)
  RUBY_ID_JUNK        = (0x07<<1)
  RUBY_ID_INTERNAL    = RUBY_ID_JUNK
  RUBY_ID_SCOPE_SHIFT = 4
  RUBY_ID_SCOPE_MASK  = (~(~0<<(RUBY_ID_SCOPE_SHIFT-1))<<1)

  ID_STATIC_SYM  = RUBY_ID_STATIC_SYM
  ID_SCOPE_SHIFT = RUBY_ID_SCOPE_SHIFT
  ID_SCOPE_MASK  = RUBY_ID_SCOPE_MASK
  ID_LOCAL       = RUBY_ID_LOCAL
  ID_INSTANCE    = RUBY_ID_INSTANCE
  ID_GLOBAL      = RUBY_ID_GLOBAL
  ID_ATTRSET     = RUBY_ID_ATTRSET
  ID_CONST       = RUBY_ID_CONST
  ID_CLASS       = RUBY_ID_CLASS
  ID_JUNK        = RUBY_ID_JUNK
  ID_INTERNAL    = RUBY_ID_INTERNAL
end
